# Con Compose v2 ya no es necesario "version", pero puedes dejarlo si quieres.
name: postgres-stack

volumes:
  postgresDB-volume:

networks:
  postgresDB-network:

services:
  postgres:
    container_name: ${CONTAINER_NAME}
    image: postgres:15
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # Vinculas el volumen que se crea por docker
      - postgresDB-volume:/var/lib/postgresql/data
      # Vinculas el volumen que tu creas localmente
      #- ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgresDB-network

  # Opcional: GUI liviana para administrar la DB
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - postgresDB-network